config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => { registrations: 'registrations' }

  root 'posts#index'
  resources :posts do
    resources :comments do
      member do
        get 'mark_spam'
        get 'vote'
      end
    end
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      if user.role? :admin
        can :access, :rails_admin
        can :dashboard
        can :manage, :all
      end
      if user.role? :registered_user
        can :manage, :Post
        can :manage, :Comment
      end
      if user.roles == nil
        can :access, :home
        can :read, :Post
        can :read, :Comment
      end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user, :foreign_key => :commented_by ,:class_name =>"User"
  has_many :votes

  validates_presence_of :description, :commented_by
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :imageable, polymorphic: true
  has_attached_file :attachment,
    :styles => {:medium => "300x300>",
      :thumb => "60x60>"}, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :attachment, content_type: /\Aimage\/.*\Z/
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  belongs_to :user, :foreign_key => :author_id ,:class_name =>"User"
  validates_presence_of :title, :description, :author_id

  has_many :images, as: :imageable, dependent: :destroy
  accepts_nested_attributes_for :images

end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts, :foreign_key => :author_id ,:class_name =>"Post", dependent: :destroy
  has_many :comments, :foreign_key => :commented_by ,:class_name =>"Comment", dependent: :destroy
  has_and_belongs_to_many :roles

  has_many :images, as: :imageable, dependent: :destroy
  accepts_nested_attributes_for :images
  has_many :votes

  validates_presence_of :name

  def role?(role)
    return !!self.roles.find_by_name(role.to_s)
  end

  def vote?(comment,flag)
    self.votes.where("comment_id =? AND value =?",comment.id,flag)
  end

end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :comment

  scope :votes_up, -> (comment_id)  {where(comment_id: comment_id, value: true).count}
  scope :votes_down, -> (comment_id)  {where(comment_id: comment_id, value: false).count}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :authenticate_user!
  rescue_from CanCan::AccessDenied do |exception|
    flash.now[:notice] = "Access denied!"
    redirect_to main_app.root_path, :alert => exception.message
  end

  def after_sign_in_path_for(resource)
    if current_user && (current_user.role? :admin)
      rails_admin.dashboard_path
    else
      root_url
    end
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  respond_to :html, :json

  def create
    @post = Post.find(params[:post_id])
    respond_to do |format|
      @comment = @post.comments.build(comment_params)
      if @comment.save
        format.js
      else
        @errors = @comment.errors.full_messages.to_sentence
        format.js
      end
    end
  end

  def mark_spam
    @post = Post.find(params[:post_id])
    respond_to do |format|
      @comment = Comment.find(params[:id])
      if @comment.update(spam: true)
        format.js
      end
    end
  end

  def vote
    get_params(params[:post_id],params[:id])
    flag = params[:flag]
    voted = Vote.where(comment_id: @comment.id,user_id: current_user.id).first
    respond_to do |format|
      if voted.blank?
        Vote.create(value: flag, user_id: current_user.id, comment_id: @comment.id)
      elsif voted.present? && voted.value.to_s != flag
        voted.update_attributes(value: flag)
      elsif voted.present? && voted.value.to_s == flag
        voted.destroy
      end
      format.js
    end
  end

  def get_params(post_id,comment_id)
    @post = Post.find(post_id)
    @comment = Comment.find(comment_id)
  end

  def destroy
    @comment = Comment.find(params[:id])
    post = @comment.post
    @comment.destroy if @comment.user == current_user
    redirect_to post
  end

  def comment_params
    params.require(:comment).permit(:description, :commented_by)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  skip_before_filter :authenticate_user!, :only => [:index, :show]
  before_action :set_post, only: [ :edit, :update, :destroy]

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find( params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to @post, notice: 'Post was successfully created.'
    else
      @errors = @post.errors.full_messages.to_sentence
      render :new
    end
  end

  def edit
    @post = Post.find( params[:id])
  end

  def update
    if @post.user == current_user
      respond_to do |format|
        if @post.update(post_params)
          format.html { redirect_to @post, notice: 'Post was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: 'edit' }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to @post, notice: 'You are not supposed to edit others post'
    end
  end

  def destroy
    if @post.user == current_user
      @post.image = nil
      @post.save
      @post.destroy
    else
      redirect_to @post, notice: 'You are not supposed to delete others post'
    end
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:title, :description, :author_id, images_attributes: [:attachment])
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  after_filter :add_role

  protected

  def add_role
    if resource.persisted? # user is created successfuly
      role = Role.where(name: "registered_user").first_or_create
      resource.roles << role
    end
  end

  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password, images_attributes: [:attachment])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment_contents.html.erb
<% if @errors.present? %>
    <%= @errors%>
  <% end %>
<% post.comments.each do |com| %>
    <p>
      <% class_name =   com.spam ? 'warn_spam' : 'nostyle' %>
      <div class = "<%= class_name%> "><%= com.description%></div>
      <div><%= image_tag com.user.images.first.attachment.url(:thumb) if com.user.images.present? %></div>
      <%=com.user.name%> : <%= com.created_at.strftime("%d-%b-%y at %l:%M")%><br />
      <% if user_signed_in? && com.user == current_user%>
        <%= link_to 'Destroy', [post,com], method: :delete, data: { confirm: 'Are you sure?' } %>
      <%end%>
      <%= link_to 'Mark Spam',mark_spam_post_comment_path(post,com), method: :get, remote: true %>
      <% class_up =   (current_user.vote?(com,true).present?) ? 'warn_spam' : 'nostyle' %>
      <% button_text =   (current_user.vote?(com,true).present?) ? 'Voted Up' : 'Vote Up' %>
      <%= link_to "#{button_text}",vote_post_comment_path(post,com,:flag => true), class: "#{class_up}", method: :get, remote: true %>
      <% class_down =   (current_user.vote?(com,false).present?) ? 'warn_spam' : 'nostyle' %>
      <% button_text =   (current_user.vote?(com,false).present?) ? 'Voted Down' : 'Vote Down' %>
      <%= link_to "#{button_text}",vote_post_comment_path(post,com,:flag => false), class: "#{class_down}", method: :get, remote: true %>
    </p>
<% end %>
<% if user_signed_in? %>
  <%= form_for [post, post.comments.build] , remote: true do |f| %>
    <p>
      <div>
        <%= f.label :description, "Comment Description" %><br />
        <%= f.text_area :description %>
        <%= f.hidden_field :commented_by, value: current_user.id%>
      </div>
    </p>
    <p>
      <%= f.submit "Add Comment" %>
    </p>
  <% end %>
<% end %>

app/views/comments/create.js.erb
$("#addcmnt").html("<%= escape_javascript(render(:partial => 'comment_contents',:locals => {post: @post})).html_safe %>");

app/views/comments/mark_spam.js.erb
$("#addcmnt").html("<%= escape_javascript(render(:partial => 'comment_contents',:locals => {post: @post})).html_safe %>");

app/views/comments/vote.js.erb
$("#addcmnt").html("<%= escape_javascript(render(:partial => 'comment_contents',:locals => {post: @post})).html_safe %>");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blogpost</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>

  <p class="navbar-text pull-right">
    <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong>.
      <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
      <% if current_user.images.present? %>
        <span class="round-image-50"><%= image_tag(current_user.images.first.attachment.url(:thumb)) %></span>
      <% end %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
      <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
    <% end %>
  </p>

  <%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post, :html => { :multipart => true } do |f| %>
  <% if @errors.present? %>
    <div><%= @errors %></div>
  <% end %>

  <div>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
    <%= f.hidden_field :author_id, value: current_user.id%>
  </div>
  <div>
    Upload Image
    <%= f.fields_for :images, 2.times {@post.images.build} do |ph| %>
      <%= ph.file_field :attachment %>
    <% end%>
  </div>
  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit your post</h1>
<% if @post.user == current_user %>
  <%= render 'form' %>
<% else %>
  <%= 'You are not supposed to edit others post' %><br>
<% end %>

<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Blog AnyThing..!!</h1>

<% @posts.each do |post| %>
  <h2><%= link_to post.title, post_path(post.to_param) %></h2>
  <%if post.images.present? %>
    <p>
      <% post.images.each do |image| %>
        <%= image_tag image.attachment.url(:medium) %>
      <% end %>
    </p>
  <% end %>
  <p>
    <%= post.description %>
  </p>
  <p><%= image_tag post.user.images.first.attachment.url(:thumb) if post.user.images.present? %>-<%= post.user.name%></p>
<% end %>
<br>
<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>
<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<h1>
  <%= @post.title %>
</h1>

<p>
  <%= @post.description %>
</p>
<%if @post.images.present? %>
  <p>
    <% @post.images.each do |image| %>
      <%= image_tag image.attachment.url(:medium) %>
    <% end %>
  </p>
<% end %>

<h2>Comments</h2>

<div id ="addcmnt">
  <%= render :partial => 'comments/comment_contents', :locals => {:post => @post} %>
</div>
<p>
  <% if user_signed_in? && @post.user == current_user %>
    <%= link_to 'Edit', edit_post_path(@post) %>
    <%= link_to 'Destroy', @post, method: :delete, data: { confirm: 'Are you sure?' }%>
  <% end %>
  <%= link_to 'Back', posts_path %>
</p>